    member()
    
    include( 'FiscalErrors.inc' ),once
    
    map
    end !* map *

! --------------------------------------------------------------------------------------------------
!
! FiscalErrors : class()
!
! --------------------------------------------------------------------------------------------------
FiscalErrors.AddError procedure( string _error_id, string _error_desc )!,private
    code
    clear( self.Qerrors )
    self.Qerrors.error_id = clip(_error_id)
    self.Qerrors.error_desc = clip(_error_desc)
    add( self.Qerrors )

FiscalErrors.GetErrorDesc procedure( string _error_id )!,string
rta         cstring(256)
    code
    rta = 'Error Desconocido/No Encontrado'
    clear( self.Qerrors )
    self.Qerrors.error_id = clip(_error_id)
    get( self.Qerrors, self.Qerrors.error_id )
    if not errorcode()
        rta = self.Qerrors.error_desc
    end !* if *

    return rta

FiscalErrors.Clean procedure()
    code
    clear( self.Qerrors )
    free( self.Qerrors )

FiscalErrors.Init procedure()
    code
    self.Qerrors &= new(TQerrors)
    self.AddError( 'SYSTEM_MUTEX_ERROR', 'Error de mutex' )
    self.AddError( 'SYSTEM_SEMAPHORE_ERROR', 'Error de semáforo' )
    self.AddError( 'SYSTEM_RTC_ERROR', 'Error de reloj de tiempo real' )
    self.AddError( 'SYSTEM_DRIVER_ERROR', 'Error de dispositivo' )
    self.AddError( 'SYSTEM_ABORTED_PROCESS', 'Proceso abortado' )
    self.AddError( 'SYSTEM_OUT_OF_MEMORY', 'Memoria agotada' )
    self.AddError( 'SYSTEM_SERVICE_ERROR', 'Error de servicio' )
    self.AddError( 'IO_READ_ERROR', 'Error de lectura' )
    self.AddError( 'IO_WRITE_ERROR', 'Error de escritura' )
    self.AddError( 'IO_OPEN_ERROR', 'Error de apertura' )
    self.AddError( 'IO_SEEK_ERROR', 'Error de posicionamiento' )
    self.AddError( 'IO_CLOSE_ERROR', 'Error de cierre' )
    self.AddError( 'IO_EOF_REACHED', 'Fin de lectura' )
    self.AddError( 'IO_MOUNT_ERROR', 'Error montando sistema de archivos' )
    self.AddError( 'IO_COMPRESS_ERROR', 'Error de compresión' )
    self.AddError( 'IO_TIMEOUT_ERROR', 'Tiempo de espera agotado' )
    self.AddError( 'IO_FS_ERROR', 'Error de sistema de archivos' )
    self.AddError( 'IO_PARAM_ERROR', 'Error de parámetros' )
    self.AddError( 'IO_NOT_OPEN', 'Dispositivo cerrado' )
    self.AddError( 'IO_DISABLED', 'Dispositivo deshabilitado' )
    self.AddError( 'IO_NOT_IMPLEMENTED', 'Función no implementada' )
    self.AddError( 'IO_WRITE_ONLY', 'Dispositivo de solo escritura' )
    self.AddError( 'IO_READ_ONLY', 'Dispositivo de solo lectura' )
    self.AddError( 'IO_ABORTED', 'Operación abortada' )
    self.AddError( 'IO_FORMAT_ERROR', 'Error de formato' )
    self.AddError( 'IO_IOCTL_ERROR', 'Error de ioctl' )
    self.AddError( 'IO_OPERATION_ERROR', 'Error en operación' )
    self.AddError( 'IO_SESSION_ERROR', 'Error de sesión' )
    self.AddError( 'SOCK_ERROR_VERSION', 'Error en versión de socket' )
    self.AddError( 'SOCK_BIND_ERROR', 'Error en bind de socket' )
    self.AddError( 'SOCK_SELECT_ERROR', 'Error en select de socket' )
    self.AddError( 'SOCK_ERROR_CONNECT', 'Error de conexión' )
    self.AddError( 'SOCK_ERROR_INIT', 'Error inicializando socket' )
    self.AddError( 'SOCK_ERROR_GENERAL', 'Error general de socket' )
    self.AddError( 'SOCK_ERROR_ACCEPT', 'Error en accept de socket' )
    self.AddError( 'SOCK_CONFIGURE_ERROR', 'Error de configuración' )
    self.AddError( 'SOCK_CONNECTION_CLOSED', 'Conexión cerrada' )
    self.AddError( 'SOCK_LISTEN_ERROR', 'Error de listen' )
    self.AddError( 'XML_TOKEN_MISMATCH', 'Token inesperado' )
    self.AddError( 'XML_EOF', 'Fin de XML' )
    self.AddError( 'XML_BAD_ENCODING', 'Codificación inválida o no soportada' )
    self.AddError( 'XML_INVALID_CHAR', 'Caracter inválido' )
    self.AddError( 'XML_TAG_UNDERFLOW', 'Tags de cierre desbalanceados' )
    self.AddError( 'XML_ATTRIBUTE_OVERFLOW', 'Demasiados atributos' )
    self.AddError( 'XML_UNEXPECTED_TEXT', 'Texto en lugar inválido' )
    self.AddError( 'XML_NO_OPEN_TAG', 'No hay tag de apertura' )
    self.AddError( 'XML_TAG_MISMATCH', 'Tag de cierre no coincide con apertura' )
    self.AddError( 'XML_INVALID_IDENTIFIER', 'Identificador inválido' )
    self.AddError( 'XML_EMPTY', 'XML vacío' )
    self.AddError( 'JSON_EOF', 'Fin de JSON' )
    self.AddError( 'JSON_SYNTAX_ERROR', 'Error de sintaxis' )
    self.AddError( 'JSON_EMPTY', 'JSON vacío' )
    self.AddError( 'CRYPTOGRAPHY_INIT', 'Error de inicialización' )
    self.AddError( 'CRYPTOGRAPHY_MEMORY_ERROR', 'Error de alojamiento de memoria' )
    self.AddError( 'CRYPTOGRAPHY_INVALID_CERTIFICATE', 'Certificado inválido' )
    self.AddError( 'CRYPTOGRAPHY_INVALID_KEY', 'Clave inválida' )
    self.AddError( 'CRYPTOGRAPHY_NOT_SUPPORTED_ALGORITHM', 'Algoritmo no soportado' )
    self.AddError( 'CRYPTOGRAPHY_ERROR', 'Error en módulo criptográfico' )
    self.AddError( 'CRYPTOGRAPHY_SSL_ERROR', 'Error en conexión SSL' )
    self.AddError( 'CRYPTOGRAPHY_SIGNATURE_FAIL', 'Error en firma digital' )
    self.AddError( 'CRYPTOGRAPHY_CERTIFICATE_DATE', 'Fecha de certificado inválida' )
    self.AddError( 'CRYPTOGRAPHY_RAND_GENERATOR_ERROR', 'Error de generación de números aleatorios' )
    self.AddError( 'CRYPTOGRAPHY_KEY_TOO_LARGE', 'Tamaño de clave excede tamaño disponible' )
    self.AddError( 'IMAGE_HEADER_ERROR', 'Error de encabezado de imagen' )
    self.AddError( 'IMAGE_FORMAT_ERROR', 'Error de formato de imagen' )
    self.AddError( 'IMAGE_READ_ERROR', 'Error de lectura de imagen' )
    self.AddError( 'POS_CF_ERROR', 'Error de controlador fiscal' )
    self.AddError( 'POS_NO_MORE_CHANGES', 'No se pueden realizar más cambios' )
    self.AddError( 'POS_INVALID_STATE', 'Error en estado de controlador' )
    self.AddError( 'POS_BAD_WORKING_MEMORY_RECORD', 'Error de memoria de trabajo' )
    self.AddError( 'POS_NO_WORKING_MEMORY', 'No hay memoria de trabajo' )
    self.AddError( 'POS_BLOCKED', 'Controlador bloqueado' )
    self.AddError( 'POS_FISCAL_MEMORY_INIT', 'Error inicializando memoria fiscal' )
    self.AddError( 'POS_USER_ERROR', 'Error de interacción con el usuario' )
    self.AddError( 'POS_INVALID_KEY', 'La clave de criptografía es inválida' )
    self.AddError( 'POS_INVALID_CERTIFICATE', 'Certificado inválido' )
    self.AddError( 'POS_SIGNATURE_ERROR', 'Error en firma digital' )
    self.AddError( 'POS_NO_MORE_DOCUMENTS', 'Sin espacio para acumular nuevos documentos' )
    self.AddError( 'POS_REPORT_GENERATION_ERROR', 'Error generando reportes AFIP' )
    self.AddError( 'POS_REPORT_GAP', 'Jornadas fiscal no consecutiva a la última bajada' )
    self.AddError( 'POS_DOCUMENT_BEYOND_FISCAL_DAY', 'Documento excede jornada fiscal' )
    self.AddError( 'POS_MEMORY_ERROR', 'Memoria dinámica agotada' )
    self.AddError( 'POS_OPEN_DOCUMENT_INVALID_DATE', 'Fecha inválida al abrir documento' )
    self.AddError( 'POS_PRINTER_ERROR', 'Error de impresora' )
    self.AddError( 'POS_FORMAT_ERROR', 'Error de formato' )
    self.AddError( 'POS_HARDWARE_ERROR', 'Error de hardware' )
    self.AddError( 'AUDIT_FULL', 'Memoria de auditoría llena' )
    self.AddError( 'AUDIT_MEMORY_ERROR', 'No hay memoria disponible para memoria de auditoría' )
    self.AddError( 'AUDIT_XML_WRITE_ERROR', 'Error de escritura en memoria de auditoría' )
    self.AddError( 'AUDIT_BAD_POINTERS', 'Error en índices de archivos de memoria de auditoría' )
    self.AddError( 'AUDIT_BAD_SEQUENCE', 'Error de secuencia de operaciones' )
    self.AddError( 'AUDIT_XML_READ_ERROR', 'Error de lectura de memoria de auditoría' )
    self.AddError( 'AUDIT_XML_OPEN_ERROR', 'Error de apertura de memoria de auditoría' )
    self.AddError( 'AUDIT_FULL_DAY', 'No hay lugar en la zeta para nuevo documento' )
    self.AddError( 'AUDIT_SECONDARY_STORAGE_CHANGED', 'Memoria de auditoría secundaria cambiada' )
    self.AddError( 'AUDIT_BAD_DATA_FORMAT', 'Error de formato de datos' )
    self.AddError( 'AUDIT_EMPTY_FISCAL_DAY_RANGE', 'Rango de jornadas fiscales no arrojó resultados' )
    self.AddError( 'AUDIT_DATE_ERROR', 'Error en fecha' )
    self.AddError( 'FISMEM_WRITE_ERROR', 'Error de escritura de memoria fiscal' )
    self.AddError( 'FISMEM_CHANGED', 'La memoria fiscal fue cambiada' )
    self.AddError( 'FISMEM_INITIALIZATION_ERROR', 'Error de inicialización de memoria fiscal' )
    self.AddError( 'FISMEM_REVISION_CHANGE', 'Cambio de revisión' )
    self.AddError( 'COMM_TIMEOUT_ERROR', 'Tiempo de espera agotado' )
    self.AddError( 'COMM_PARAM_ERROR', 'Parámetro inválido' )
    self.AddError( 'COMM_INVALID_ANSWER', 'Respuesta inválida' )
    self.AddError( 'COMM_UNRECOGNIZED_', 'Comando no reconocido' )
    self.AddError( 'COMM_GENERAL_ERROR', 'Error de comunicaciones' )
    self.AddError( 'COMM_ERROR_HOST', 'Error en destino de conexión' )
    self.AddError( 'COMM_MAX_RETRIES', 'Reintentos agotados' )
    self.AddError( 'COMM_SYNTAX_ERROR', 'Error de sintaxis' )
    self.AddError( 'COMM_NOTFOUND_ERROR', 'No encontrado' )
    self.AddError( 'COMM_INVALID_DATA_FORMAT', 'Formato de datos inválido' )
    self.AddError( 'COMM__ERROR', 'Error en comando' )
    self.AddError( 'COMM_NOT_SUPPORTED', 'Comando u operación no soportada' )
    self.AddError( 'COMM_UNAUTHORIZED_IP', 'Cliente no autorizado' )
    self.AddError( 'CMD_UNRECOGNIZED_', 'Operación desconocida' )
    self.AddError( 'CMD_PARAM_NOT_PRESENT', 'Parámetro obligatorio no especificado' )
    self.AddError( 'CMD_PARAM_SYNTAX_ERROR', 'Error sintáctico en parámetro' )
    self.AddError( 'CMD_PARAM_OUT_OF_RANGE', 'Parámetro fuera de su rango de validez' )
    self.AddError( 'CMD_PARAM_SEMANTIC_ERROR', 'Error semántico en parámetro' )
    self.AddError( 'CMD_FIELD_NOT_LOADED', 'Dato obligatorio no ingresado previamente' )
    self.AddError( 'CMD_INVALID_STATE', 'Operación no válida para el estado fiscal actual' )
    self.AddError( 'CMD_INVALID_OPERATION', 'Intento de ejecución de operación no válida' )
    self.AddError( 'CMD_EXECUTION_ERROR', 'Error en ejecución de operación en curso' )
    self.AddError( 'CMD_BAD_BARCODE_LENGTH', 'Error en longitud de código de barras' )
    self.AddError( 'CMD_BAD_BARCODE_FORMAT', 'Error en formato de código de barras' )
    self.AddError( 'CMD_BAD_BARCODE_TYPE', 'Error en tipo de código de barras' )
    self.AddError( 'CMD_ABORTED_ACTION', 'Error acción abortada' )
    self.AddError( 'CMD_DATA_NOT_FOUND', 'Dato no encontrado' )
    self.AddError( 'CMD_ELECTRONIC_INVOICING_ERROR', 'Error en operación de factura electrónica' )
    self.AddError( 'CMD_ELECTRONIC_INVOICING_COMM_ERROR', 'Error de comunicaciones en operación de factura electrónica' )
    self.AddError( 'CMD_ELECTRONIC_INVOICING_PRINT_ERROR', 'Error de generación de comprobante en factura electrónica' )
    self.AddError( 'ARITHMETIC_DOCUMENT_LIMIT_OVERFLOW', 'Excede el límite de documento' )
    self.AddError( 'ARITHMETIC_END_CONSUMER_LIMIT_OVERFLOW', 'Excede limite para consumidor final' )
    self.AddError( 'ARITHMETIC_RECEIPT_LIMIT_OVERFLOW', 'Excede límite para comprobantes B' )
    self.AddError( 'ARITHMETIC_VAT_TABLE_OVERFLOW', 'Excede tabla de IVA' )
    self.AddError( 'ARITHMETIC_NEGATIVE_TOTAL', 'El total se hace negativo' )
    self.AddError( 'ARITHMETIC_NEGATIVE_VAT', 'El IVA se hace negativo' )
    self.AddError( 'ARITHMETIC_DAILY_LIMIT_OVERFLOW', 'Excede máximo diario' )
    self.AddError( 'ARITHMETIC_NO_NET_AMOUNT_FOR_TAX', 'Impuesto sin monto base' )
    self.AddError( 'ARITHMETIC_INVALID_NET_AMOUNT_FOR_DISCOUNT', 'El monto excede la base descontable' )
    self.AddError( 'ARITHMETIC_NO_TOTAL_AMOUNT_FOR_TAX', 'No hay venta previa a la emisión del tributo' )
    self.AddError( 'ARITHMETIC_TAX_AMOUNT_GREATER_THAN_PRICE', 'Impuesto interno fijo mayor a monto final del ítem' )
    self.AddError( 'ARITHMETIC_TYPE_OVERFLOW', 'Operación excede el límite numérico máximo' )
    self.AddError( 'ARITHMETIC_NEGATIVE_ADDITIONAL_TAXES', 'Los impuestos internos se hacen negativos' )
    self.AddError( 'ARITHMETIC_ZERO_SUBTOTAL', 'Subtotal cero no permitido' )
    self.AddError( 'ARITHMETIC_ZERO_AMOUNT', 'Monto cero no permitido' )
    self.AddError( 'ARITHMETIC_NEGATIVE_NET_AMOUNT', 'El monto neto se hace negativo' )
    self.AddError( 'ARITHMETIC_NEGATIVE_ITEM_ACUMULATOR', 'El acumulador de item se hace negativo' )
    self.AddError( 'ARITHMETIC_TAX_TABLE_OVERFLOW', 'Excede tabla de otros tributos' )
    self.AddError( 'DATAFILE_KEY_NOT_FOUND', 'No se han encontrado los campos clave' )
    self.AddError( 'DATAFILE_RECORD_NOT_FOUND', 'Registro no encontrado' )
    self.AddError( 'DATAFILE_DELETE_ERROR', 'Error eliminando registro' )
    self.AddError( 'DATAFILE_INDEX', 'Base de datos no indexada' )
    self.AddError( 'DATAFILE_SORT', 'Error de ordenamiento' )
    self.AddError( 'DATAFILE_KEY_ALREADY_EXISTS', 'Clave existente.' )
    self.AddError( 'DATAFILE_FIELD_NOT_FOUND', 'Campo no encontrado' )
    self.AddError( 'DATAFILE_FIELD_TYPE_ERROR', 'Valor incorrecto para el tipo del campo' )
    self.AddError( 'DATAFILE_INVALID_RECORD', 'Registro inválido' )
    self.AddError( 'DATAFILE_INVALID', 'Base de datos no pudo ser abierta' )
    self.AddError( 'DATAFILE_VERSION_ERROR', 'Base de datos de versión errónea' )
    self.AddError( 'PROTOCOL_NO_TRANSPORT', 'No hay transporte definido' )
    self.AddError( 'PROTOCOL_SIZE', 'Error en tamaño de paquete' )
    self.AddError( 'PROTOCOL_ABORTED', 'Operación abortada' )
    self.AddError( 'PROTOCOL_COMM_ANOMALY', 'Anomalía de comunicaciones' )
    self.AddError( 'PROTOCOL_WRONG_PROTOCOL', 'Protocolo equivocado' )
    self.AddError( 'PROTOCOL_INVALID_PACKET', 'Tamaño de paquete inválido' )
    self.AddError( 'PROTOCOL_MAX_RETRIES', 'Máxima cantidad de reintentos agotada' )
    self.AddError( 'PROTOCOL__REJECTED', 'Comando rechazado' )
    self.AddError( 'PROTOCOL_RESOURCE_NOT_FOUND', 'Recurso no encontrado' )
    self.AddError( 'PROTOCOL_PACKET_REJECTED', 'Paquete rechazado' )
    self.AddError( 'PROTOCOL_SYNTAX_ERROR', 'Error de sintaxis' )
    self.AddError( 'PROTOCOL_INVALID_ENCODING', 'Codificación de caracteres inválida' )
    self.AddError( 'PROTOCOL_UNKNOWN_', 'Comando desconocido' )
    self.AddError( 'PROTOCOL_CHECKSUM_MISMATCH', 'Error de suma de comprobación' )
    self.AddError( 'PROTOCOL_INVALID_SEQUENCE', 'Secuencia fuera de rango' )
    self.AddError( 'PROTOCOL_SEQUENCE_MISMATCH', 'Error en número de secuencia' )
    self.AddError( 'PROTOCOL_INVALID_CONTENT_TYPE', 'Tipo de contenido inválido' )
    self.AddError( 'INTERFACE__REJECTED', 'Comando rechazado' )
    self.AddError( 'INTERFACE_UNKNOWN_PROTOCOL', 'Protocolo desconocido' )
    self.AddError( 'INTERFACE_SYNTAX_ERROR', 'Error de sintaxis' )
    self.AddError( 'INTERFACE_UNRECOGNIZED_', 'Comando no reconocido' )
    self.AddError( 'INTERFACE_UNRECOGNIZED_FIELD', 'Campo no reconocido' )
    self.AddError( 'INTERFACE_MISSING_FIELD', 'Campo inexistente' )
    self.AddError( 'INTERFACE_INVALID_STATE', 'Estado inválido' )
    self.AddError( 'INTERFACE__ABORTED', 'Comando cancelado por el usuario' )
    self.AddError( 'COUPON_PRINTER_INVALID_IMAGE_FILE', 'Formato de imagen inválido' )
    self.AddError( 'COUPON_PRINTER_INVALID_IMAGE_SIZE', 'Tamaño de imagen inválido' )

FiscalErrors.Done procedure()
    code
    if not self.Qerrors &= NULL
        self.clean()
        dispose( self.Qerrors )
    end !* if *   

!* end *